import json
from datetime import datetime, timezone
from pathlib import Path


def flatten_tools(data):
    """Recursively flatten nested lists of tool dictionaries."""
    result = []
    for item in data:
        if isinstance(item, list):
            result.extend(flatten_tools(item))
        elif isinstance(item, dict):
            result.append(item)
    return result


def generate_html_report(json_path: str, output_path: str):
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    project = data.get("project", "Untitled Project")
    tools_data = data.get("tools", [])

    # Flatten nested lists safely
    flattened = flatten_tools(tools_data)

    # Filter out unknown or empty workflow entries
    flattened = [t for t in flattened if t.get("workflow") not in ["", "unknown", "Unknown", None]]

    timestamp = datetime.now(timezone.utc).isoformat()

    css = """
    <style>
      :root{
        --bg:#0f1724;
        --card:#0b1220;
        --muted:#94a3b8;
        --accent:#60a5fa;
        --good:#10b981;
        --bad:#ef4444;
        --glass:rgba(255,255,255,0.05);
      }
      body{
        background:linear-gradient(180deg,#071027 0%, #04111b 100%);
        color:#e6eef8;
        font-family:Inter,Segoe UI,Helvetica,Arial,sans-serif;
        margin:0;padding:32px;
      }
      .container{
        max-width:960px;
        margin:0 auto;
      }
      h1{font-size:28px;color:var(--accent);margin-bottom:8px;}
      .meta{color:var(--muted);margin-bottom:24px;}
      .grid{
        display:grid;
        grid-template-columns:repeat(auto-fill,minmax(280px,1fr));
        gap:18px;
      }
      .card{
        background:var(--card);
        padding:18px;
        border-radius:14px;
        box-shadow:0 4px 20px rgba(0,0,0,0.4);
        transition:transform .2s ease, box-shadow .2s ease;
      }
      .card:hover{
        transform:translateY(-3px);
        box-shadow:0 6px 24px rgba(0,0,0,0.6);
      }
      .workflow{
        font-size:18px;
        color:var(--accent);
        font-weight:600;
        margin-bottom:6px;
      }
      .field{
        font-size:14px;
        color:var(--muted);
        margin:2px 0;
      }
      .badge{
        background:var(--glass);
        color:var(--good);
        font-size:12px;
        padding:2px 8px;
        border-radius:6px;
        margin-left:6px;
      }
      footer{
        margin-top:32px;
        text-align:center;
        font-size:13px;
        color:var(--muted);
      }
      @media(max-width:600px){
        body{padding:16px;}
      }
    </style>
    """

    cards = ""
    for tool in flattened:
        workflow = str(tool.get("workflow", "")).strip()
        run_id = str(tool.get("run_id", "")).strip()
        domain = str(tool.get("domain", "")).strip()
        ts = str(tool.get("timestamp", "")).strip()
        fc = str(tool.get("file_count", "")).strip()

        if not workflow:
            continue

        cards += f"""
        <div class="card">
          <div class="workflow">{workflow}<span class="badge">#{run_id}</span></div>
          <div class="field"><b>Domain:</b> {domain or "N/A"}</div>
          <div class="field"><b>Timestamp:</b> {ts or "N/A"}</div>
          <div class="field"><b>File Count:</b> {fc or "0"}</div>
        </div>
        """

    html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <title>Project Report: {project}</title>
      {css}
    </head>
    <body>
      <div class="container">
        <h1>Project Report: {project}</h1>
        <div class="meta">Generated on: {timestamp} UTC</div>

        <div class="grid">
          {cards}
        </div>

        <footer>Generated by Websi3 Scanner — Enhanced DarkGlass Theme</footer>
      </div>
    </body>
    </html>
    """

    Path(output_path).write_text(html, encoding="utf-8")
    print(f" HTML report generated: {output_path}")


if __name__ == "__main__":
    import sys
    if len(sys.argv) != 3:
        print("Usage: python generate_html_report.py <input_json> <output_html>")
        sys.exit(1)

    generate_html_report(sys.argv[1], sys.argv[2])
